hw-04 done
Tank-Nkolay/nodejs-homework-rest-api pull request #6
Opened 2023-01-20 23:09 UTC by Tank-Nkolay

2023-01-21 20:11 UTC, NadyaHristuk requested changes

2023-01-21 20:11 UTC, NadyaHristuk commented on src/controllers/updateSubsc.js
> +  console.log(_id);
console.log(_id);

2023-01-21 20:11 UTC, NadyaHristuk commented on src/routes/api/users.js
> +router.patch("/", auth, patchUpdateSubscValidation, asyncWrapper(updateSubsc));
Не знайшла роут - Створити ендпоінт [/users/current](https://textbook.edu.goit.global/lms-nodejs-homework/v1/uk/docs/hw-04/#current-user-request)

2023-01-22 07:45 UTC, Tank-Nkolay commented on src/controllers/updateSubsc.js
> +  console.log(_id);
виправив

2023-01-22 07:46 UTC, Tank-Nkolay commented on src/routes/api/users.js
> +router.patch("/", auth, patchUpdateSubscValidation, asyncWrapper(updateSubsc));
виправив, переніс роут в routes/api/users

2023-01-22 18:47 UTC, merged